# Generated by Django 3.0.6 on 2020-05-22 13:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('src', '0002_auto_20200522_1500'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('user', 'date')},
        ),
    ]
