# Generated by Django 3.0.8 on 2020-07-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_presence_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('free_slots', models.IntegerField()),
                ('closed', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='djouser',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
