# Generated by Django 3.0.6 on 2020-07-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20200718_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.DjoUser')),
            ],
            options={
                'verbose_name_plural': 'MacAddresses',
                'order_with_respect_to': 'user',
            },
        ),
    ]
