# Generated by Django 3.0.6 on 2020-07-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_macaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaddress',
            name='mac',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['date', 'user'], name='src_presenc_date_c6e781_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['date'], name='src_presenc_date_891774_idx'),
        ),
    ]
