# Generated by Django 3.0.6 on 2020-07-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20200726_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='seen_by',
            field=models.CharField(choices=[('mac', 'Mac Adres'), ('manual', 'Handmatig Aangemeld')], default='manual', max_length=6),
        ),
    ]
