# Generated by Django 3.1.7 on 2021-03-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_presence_seen_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macaddress',
            options={'verbose_name_plural': 'Mac Addresses'},
        ),
        migrations.AddField(
            model_name='presence',
            name='pod',
            field=models.CharField(choices=[('m', 'Ochtend'), ('a', 'Middag'), ('e', 'Avond')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='specialdate',
            name='pod',
            field=models.CharField(choices=[('m', 'Ochtend'), ('a', 'Middag'), ('e', 'Avond')], max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['date', 'pod'], name='src_presenc_date_3c722b_idx'),
        ),
    ]
