# Generated by Django 3.1.7 on 2021-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_auto_20210310_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdate',
            name='pod',
            field=models.CharField(blank=True, choices=[('m', 'Ochtend'), ('a', 'Middag'), ('e', 'Avond')], max_length=1, null=True),
        ),
    ]
