# Generated by Django 3.1.7 on 2021-03-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_auto_20210310_1853'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['date', 'user', 'pod'], name='src_presenc_date_b8b9f2_idx'),
        ),
    ]
