# Generated by Django 3.2.7 on 2021-11-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_auto_20211105_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='over_18',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
