# Generated by Django 3.2.7 on 2021-11-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_auto_20211128_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fri', 'Vrijdag'), ('sat', 'Zaterdag')], max_length=3)),
                ('pod', models.CharField(choices=[('m', 'Ochtend'), ('a', 'Middag'), ('e', 'Avond')], max_length=1)),
                ('description', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('name', 'pod')},
            },
        ),
    ]
