# Generated by Django 3.2.7 on 2021-11-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_slot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('user', 'date', 'pod')},
        ),
    ]
