# Generated by Django 3.2.12 on 2022-03-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_alter_presence_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialdate',
            name='announcement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
