# Generated by Django 4.1.7 on 2023-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_remove_userinfo_age_userinfo_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='stripcard_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='stripcard_used',
            field=models.IntegerField(default=0),
        ),
    ]
