# Generated by Django 5.0.7 on 2024-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0020_userinfo_stripcard_count_userinfo_stripcard_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='name',
            field=models.CharField(choices=[('mon', 'Maandag'), ('tue', 'Dinsdag'), ('wed', 'Woensdag'), ('thu', 'Donderdag'), ('fri', 'Vrijdag'), ('sat', 'Zaterdag'), ('sun', 'Zondag')], max_length=3),
        ),
    ]
