# Generated by Django 5.0.8 on 2024-08-09 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0021_alter_slot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='stripcard_expires',
            field=models.DateField(default=datetime.date(2099, 1, 1)),
        ),
    ]
