# Generated by Django 6.0.4 on 2026-04-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_userinfo_stripcard_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='opens_djo',
            field=models.BooleanField(default=False),
        ),
    ]
